/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tweetgui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.MatteBorder;
import static tweetgui.LogInWindow.loggedIn;

/**
 *
 * @author johnr
 */

public class MainWindow extends javax.swing.JFrame {
    public static ServerCommunicator toServer = new ServerCommunicator(); 
    public static String loggedIn = null;
    public static LinkedList<String> following = new LinkedList<>();
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        if(loggedIn != null)
            following = toServer.retrieveFollowing(loggedIn);
        tPanel = new TweetPane(); 
        makePostBut.setEnabled(false);
        refreshBut.setEnabled(false);
        searchBut.setEnabled(false);
        viewPMBut.setEnabled(false);
    }
    
    public MainWindow(String loggedIn, boolean search, String sTopic) {
        initComponents();
        this.loggedIn = loggedIn;
        String topic = sTopic;
        if(loggedIn != null)
            following = toServer.retrieveFollowing(loggedIn);
        
        if(search == true || topic != null){
            tPanel = new TweetPane(topic);
        }
        else
            tPanel = new TweetPane(); 
        makePostBut.setEnabled(false);
        refreshBut.setEnabled(false);
        searchBut.setEnabled(false);
        viewPMBut.setEnabled(false);
    }
    
    public static void enableBut(){
        makePostBut.setEnabled(true);
        refreshBut.setEnabled(true);
        searchBut.setEnabled(true);
        viewPMBut.setEnabled(true);
    }
    
    public static void disableButtons(){
        makePostBut.setEnabled(false);
        refreshBut.setEnabled(false);
        searchBut.setEnabled(false);
        viewPMBut.setEnabled(false);
    }
    
    public void refreshMainWindow(boolean search){
        String topic = null;
        if(search == true){
            topic = MainWindow.searchField.getText();
        }
        MainWindow refreshed = new MainWindow(loggedIn, search, topic);
        invalidate();
        dispose();
        MainWindow.enableBut();
        refreshed.setVisible(true);
        
    }
    
    public void refreshMainWindow(String username, boolean search){
        String topic = null;
        if(search == true){
            topic = MainWindow.searchField.getText();
        }
        else
            topic = username;
        MainWindow refreshed = new MainWindow(loggedIn, search, topic);
        invalidate();
        dispose();
        MainWindow.enableBut();
        refreshed.setVisible(true);
        
    }
    
    public static void logOff(){
        loggedIn = null;
        following = null; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jDialog4 = new javax.swing.JDialog();
        jDialog5 = new javax.swing.JDialog();
        jDialog6 = new javax.swing.JDialog();
        jToolBar1 = new javax.swing.JToolBar();
        jDialog7 = new javax.swing.JDialog();
        jDialog8 = new javax.swing.JDialog();
        jDialog9 = new javax.swing.JDialog();
        headerPanel = new javax.swing.JPanel();
        refreshBut = new javax.swing.JButton();
        logRegBut = new javax.swing.JButton();
        searchBut = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        makePostBut = new javax.swing.JButton();
        tPanel = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        notifArea = new javax.swing.JTextArea();
        viewPMBut = new javax.swing.JButton();
        logLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog5Layout = new javax.swing.GroupLayout(jDialog5.getContentPane());
        jDialog5.getContentPane().setLayout(jDialog5Layout);
        jDialog5Layout.setHorizontalGroup(
            jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog5Layout.setVerticalGroup(
            jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog6Layout = new javax.swing.GroupLayout(jDialog6.getContentPane());
        jDialog6.getContentPane().setLayout(jDialog6Layout);
        jDialog6Layout.setHorizontalGroup(
            jDialog6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog6Layout.setVerticalGroup(
            jDialog6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jToolBar1.setRollover(true);

        javax.swing.GroupLayout jDialog7Layout = new javax.swing.GroupLayout(jDialog7.getContentPane());
        jDialog7.getContentPane().setLayout(jDialog7Layout);
        jDialog7Layout.setHorizontalGroup(
            jDialog7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog7Layout.setVerticalGroup(
            jDialog7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog8Layout = new javax.swing.GroupLayout(jDialog8.getContentPane());
        jDialog8.getContentPane().setLayout(jDialog8Layout);
        jDialog8Layout.setHorizontalGroup(
            jDialog8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog8Layout.setVerticalGroup(
            jDialog8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog9Layout = new javax.swing.GroupLayout(jDialog9.getContentPane());
        jDialog9.getContentPane().setLayout(jDialog9Layout);
        jDialog9Layout.setHorizontalGroup(
            jDialog9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog9Layout.setVerticalGroup(
            jDialog9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        refreshBut.setText("Refresh");
        refreshBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButActionPerformed(evt);
            }
        });

        if(loggedIn == null)
        logRegBut.setText("LogIn/Register");
        else
        logRegBut.setText("View Your Page");
        logRegBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logRegButMouseClicked(evt);
            }
        });

        searchBut.setText("Search");
        searchBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButActionPerformed(evt);
            }
        });

        makePostBut.setText("Make Post");
        makePostBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makePostButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(refreshBut)
                .addGap(5, 5, 5)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(searchBut, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(makePostBut, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logRegBut))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(refreshBut)
                .addComponent(searchField)
                .addComponent(searchBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(makePostBut)
                .addComponent(logRegBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tPanelLayout = new javax.swing.GroupLayout(tPanel);
        tPanel.setLayout(tPanelLayout);
        tPanelLayout.setHorizontalGroup(
            tPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 852, Short.MAX_VALUE)
        );
        tPanelLayout.setVerticalGroup(
            tPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        notifArea.setColumns(20);
        notifArea.setRows(5);
        notifArea.setText("Notifications to the user\n");
        jScrollPane7.setViewportView(notifArea);

        viewPMBut.setText("View Private Messages");
        viewPMBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPMButActionPerformed(evt);
            }
        });

        if(MainWindow.loggedIn == null)
        logLabel.setText("No one is logged in.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addComponent(viewPMBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(viewPMBut)
                        .addGap(5, 5, 5)
                        .addComponent(logLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 424, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void makePostButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makePostButActionPerformed
        MakePost postWin = new MakePost(MainWindow.this,true);
        postWin.setDefaultCloseOperation(MakePost.DISPOSE_ON_CLOSE);
        postWin.setVisible(true);
    }//GEN-LAST:event_makePostButActionPerformed

    private void logRegButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logRegButMouseClicked
        if(loggedIn == null){
            LogInWindow logWin = new LogInWindow(MainWindow.this,true);
            logWin.setDefaultCloseOperation(logWin.DISPOSE_ON_CLOSE);
            logWin.setVisible(true);
        }
        else{
            UserPage urPage = new UserPage(MainWindow.this, true, loggedIn);
            urPage.setDefaultCloseOperation(urPage.DISPOSE_ON_CLOSE);
            urPage.setVisible(true);
        }    
    }//GEN-LAST:event_logRegButMouseClicked

    private void viewPMButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPMButActionPerformed
            PrivMessList privMess = new PrivMessList();
            privMess.setDefaultCloseOperation(privMess.DISPOSE_ON_CLOSE);
            privMess.setVisible(true);   
            viewPMBut.setEnabled(false);
    }//GEN-LAST:event_viewPMButActionPerformed

    private void refreshButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButActionPerformed
            refreshMainWindow(false);
    }//GEN-LAST:event_refreshButActionPerformed
//
    private void searchButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButActionPerformed
            refreshMainWindow(true);
    }//GEN-LAST:event_searchButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MainWindow mWindow = new MainWindow();
                mWindow.setDefaultCloseOperation(MainWindow.EXIT_ON_CLOSE);
                mWindow.setVisible(true);
                mWindow.addWindowListener(new WindowAdapter(){
                    public void windowClosing(WindowEvent e){
                        if(MainWindow.loggedIn != null)
                            toServer.loggingOff(MainWindow.loggedIn);
                    }
                });               
            }
        });
        
    }
    
    public class TweetPane extends JPanel{
        private JPanel tweetList;
        private LinkedList<JPanel> tweets;
        
        public TweetPane(){
            tweets = getTweetPanels(null);
            tPanel.setLayout(new BorderLayout());
            
            tweetList = new JPanel(new GridBagLayout());
            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridwidth = GridBagConstraints.REMAINDER;
            gbc.weightx = 1;
            gbc.weighty = 1;
            tweetList.add(new JPanel(), gbc);
            
            tPanel.add(new JScrollPane(tweetList));
            if(tweets != null)
                for(JPanel tweet : tweets){
                    tweet.setBorder(new MatteBorder(0,0,1,0, Color.GRAY));
                    gbc.gridwidth = GridBagConstraints.REMAINDER;
                    gbc.weightx = 1;
                    gbc.fill = GridBagConstraints.HORIZONTAL;
                    tweetList.add(tweet, gbc, 0);

                    validate();
                } 
        }
        
        public TweetPane(String topic){
            tweets = getTweetPanels(topic);
            
         
            tPanel.setLayout(new BorderLayout());
            
            tweetList = new JPanel(new GridBagLayout());
            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridwidth = GridBagConstraints.REMAINDER;
            gbc.weightx = 1;
            gbc.weighty = 1;
            tweetList.add(new JPanel(), gbc);
            
            tPanel.add(new JScrollPane(tweetList));
            
            for(JPanel tweet : tweets){
                tweet.setBorder(new MatteBorder(0,0,1,0, Color.GRAY));
                gbc.gridwidth = GridBagConstraints.REMAINDER;
                gbc.weightx = 1;
                gbc.fill = GridBagConstraints.HORIZONTAL;
                tweetList.add(tweet, gbc, 0);
                
                validate();
            } 
        }
        
        //sets a tweet panel for all of the users tweets
        private LinkedList<JPanel> getTweetPanels(String topic){
            LinkedList<JPanel> tweets = new LinkedList<>();
            ArrayList<Tweet> toRead = getTweets(topic);
            
            if(toRead != null)
                for(Tweet t : toRead){
                    JButton viewPage = new JButton();
                    JLabel nameLbl = new JLabel();
                    JLabel tweetTxt = new JLabel();
                    JPanel tweetPanel = new JPanel();

                    tweetTxt.setText(t.getText());
                    nameLbl.setText(t.getUsername());
                    viewPage.setText("View Page");

                    viewPage.addActionListener(new ActionListener(){
                        @Override
                        public void actionPerformed(ActionEvent ae) {
                            UserPage uPage = new UserPage(MainWindow.this, true, t.getUsername());
                            uPage.setDefaultCloseOperation(UserPage.DISPOSE_ON_CLOSE);
                            uPage.setVisible(true);
                        }
                    });

                    javax.swing.GroupLayout tpLayout = new javax.swing.GroupLayout(tweetPanel);
                    tweetPanel.setLayout(tpLayout);
                    tpLayout.setHorizontalGroup(
                        tpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tpLayout.createSequentialGroup()
                            .addComponent(viewPage, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(428, Short.MAX_VALUE))
                        .addComponent(tweetTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    );
                    tpLayout.setVerticalGroup(
                        tpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tpLayout.createSequentialGroup()
                            .addGroup(tpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(viewPage, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameLbl))
                            .addGap(7, 7, 7)
                            .addComponent(tweetTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                    );

                    tweets.add(tweetPanel);
                }

            return tweets;
        }
        
        private ArrayList<Tweet> getTweets(String topic){
            
            ArrayList<Tweet> toRead = new ArrayList<>();
            if(topic == null){
                if(MainWindow.loggedIn == null){
                    toRead = new ArrayList<>();
                }
                else
                    System.out.println("first");
                    toRead = toServer.retrieveTweets(MainWindow.loggedIn);
            }
            else{
                System.out.println("Second");
                toRead = toServer.search(topic);
            }
            if(toRead == null){
                JOptionPane jOPane = new JOptionPane();
                JOptionPane.showMessageDialog(jOPane, "No posts with that tag");
                return new ArrayList<>();
            }
            return toRead;
        }
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel headerPanel;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JDialog jDialog5;
    private javax.swing.JDialog jDialog6;
    private javax.swing.JDialog jDialog7;
    private javax.swing.JDialog jDialog8;
    private javax.swing.JDialog jDialog9;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JToolBar jToolBar1;
    public static javax.swing.JLabel logLabel;
    public static javax.swing.JButton logRegBut;
    private static javax.swing.JButton makePostBut;
    private javax.swing.JTextArea notifArea;
    private static javax.swing.JButton refreshBut;
    private static javax.swing.JButton searchBut;
    private static javax.swing.JTextField searchField;
    public javax.swing.JPanel tPanel;
    private static javax.swing.JButton viewPMBut;
    // End of variables declaration//GEN-END:variables
}
