/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tweetgui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.MatteBorder;

/**
 *
 * @author johnr
 */
public class UserPage extends javax.swing.JFrame {
    /**
     * Creates new form UserPage
     */
    private static String username;
    private ServerCommunicator toServer = new ServerCommunicator();
    private LinkedList<String> thFollowers = null;
    private LinkedList<String> thFollowing = null;
    private MainWindow parent;
            
    
    public UserPage(MainWindow parent, boolean modal, String username) {
        this.parent =  parent;
        this.username = username;
        System.out.println(username);
        this.initComponentsUP();
        thFollowers = toServer.retrieveFollowers(username);
        thFollowing = toServer.retrieveFollowing(username);
        nameLbl.setText(username);
        if(thFollowers != null)
            erBut.setText("" + thFollowers.size());
        else
            erBut.setText("None");
        
        if(thFollowing != null)
            ingBut.setText("" + thFollowing.size()); 
        else
            ingBut.setText("None");
        
        if(thFollowers.contains(MainWindow.loggedIn))
            folBut.setText("Unfollow");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponentsUP(){
    /*
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        */
        nameLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        erBut = new javax.swing.JButton();
        ingBut = new javax.swing.JButton();
        folBut = new javax.swing.JButton();
        postsBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameLbl.setText("jLabel1");

        jLabel1.setText("Followers");

        jLabel2.setText("Following");

        jLabel3.setText("Posts");

        erBut.setText("jButton1");
        erBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erButActionPerformed(evt);
            }
        });

        ingBut.setText("jButton1");
        ingBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingButActionPerformed(evt);
            }
        });

        if(MainWindow.loggedIn.contentEquals(username)){
            folBut.setText("Log Out");
        }
        else{
            if(thFollowing != null && thFollowing.contains(username)){
                folBut.setText("Unfollow");
            }
            else{
                folBut.setText("Follow");
            }
        }
        folBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folButActionPerformed(evt);
            }
        });

        postsBut.setText("View Posts");
        postsBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postsButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(erBut, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(ingBut, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(postsBut)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameLbl)
                .addGap(280, 280, 280))
            .addGroup(layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(folBut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(nameLbl)
                .addGap(9, 9, 9)
                .addComponent(folBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(erBut)
                    .addComponent(ingBut)
                    .addComponent(postsBut))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void erButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_erButActionPerformed
            UserPanels up = new UserPanels(thFollowers, parent);
            up.setDefaultCloseOperation(up.DISPOSE_ON_CLOSE);
            up.setVisible(true);
    }//GEN-LAST:event_erButActionPerformed

    private void ingButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingButActionPerformed
            UserPanels up = new UserPanels(thFollowing, parent);
            up.setDefaultCloseOperation(up.DISPOSE_ON_CLOSE);
            up.setVisible(true);
    }//GEN-LAST:event_ingButActionPerformed

    private void folButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folButActionPerformed
        if(folBut.getText().equals("Follow")){
            toServer.followUser(MainWindow.loggedIn, username);
            MainWindow.following.add(username);
            thFollowing.add(username);
            folBut.setText("Unfollow");
        }
        else if(folBut.getText().equals("Log Out")){
            JOptionPane.showMessageDialog(new JOptionPane(), toServer.loggingOff(username));
            MainWindow.logOff();
            MainWindow.logLabel.setText("No one is logged In");
            MainWindow.logRegBut.setText("Log In/Register");
            parent.refreshMainWindow(false);
            MainWindow.disableButtons();
        }
        else{
            toServer.unfollowUser(MainWindow.loggedIn, username);
            MainWindow.following.remove(username);
            thFollowing.remove(username);
        }    
        this.dispose();
    }//GEN-LAST:event_folButActionPerformed

    private void postsButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postsButActionPerformed
        parent.refreshMainWindow(username, false);
        this.dispose();
    }//GEN-LAST:event_postsButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPage(new javax.swing.JFrame(), true, username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton erBut;
    private javax.swing.JButton folBut;
    private javax.swing.JButton ingBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JButton postsBut;
    // End of variables declaration//GEN-END:variables
}
